export interface Product {
  id: number;
  name: string;
  store: string;
  subtitle?: string;
  price: number;
  oldPrice: number;
  discount: string;
  rating: number;
  reviews: number;
  labels: string[];
  image: string;
  sizes: string[];
  colors: string[];
  deliveryEstimate: string;
  stockStatus: "In Stock" | "Low Stock" | "Out of Stock";
}

export const masterProducts: Product[] = [
  {
    id: 1,
    name: "Black Formal Shirt",
    store: "Fashion Hub",
    price: 799,
    oldPrice: 1299,
    discount: "38% OFF",
    rating: 4.6,
    reviews: 1200,
    labels: ["Best Seller"],
    image: "/images/products/shirt.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Stone"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "In Stock",
  },
  {
    id: 2,
    name: "Black Premium Shirt",
    store: "Urban Tribe",
    price: 699,
    oldPrice: 999,
    discount: "30% OFF",
    rating: 4.5,
    reviews: 890,
    labels: ["30% OFF"],
    image: "/images/products/shirt.jpeg",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Charcoal"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "Low Stock",
  },
  {
    id: 3,
    name: "Black Slim Fit Shirt",
    store: "Street Style",
    price: 749,
    oldPrice: 1199,
    discount: "37% OFF",
    rating: 4.7,
    reviews: 2100,
    labels: ["Fast Delivery"],
    image: "/images/bestsellers/cargo-pant.jpeg",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue"],
    deliveryEstimate: "Delivery in 2 Hours",
    stockStatus: "In Stock",
  },
  {
    id: 4,
    name: "Black Casual Shirt",
    store: "Ethnic Villa",
    price: 649,
    oldPrice: 999,
    discount: "35% OFF",
    rating: 4.4,
    reviews: 760,
    labels: ["New"],
    image: "/images/bestsellers/casual-shirt.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Beige", "Olive"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
  {
    id: 5,
    name: "Black Cotton Shirt",
    store: "Fashion Hub",
    price: 799,
    oldPrice: 1299,
    discount: "38% OFF",
    rating: 4.6,
    reviews: 1130,
    labels: ["Best Seller"],
    image: "/images/bestsellers/linen-shirt.jpeg",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "White"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "In Stock",
  },
  {
    id: 6,
    name: "Black Linen Shirt",
    store: "Urban Tribe",
    price: 899,
    oldPrice: 1299,
    discount: "31% OFF",
    rating: 4.5,
    reviews: 680,
    labels: ["Fast Delivery"],
    image: "/images/bestsellers/linen-shirt.jpeg",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Beige"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
  {
    id: 7,
    name: "Black Striped Shirt",
    store: "Street Style",
    price: 599,
    oldPrice: 799,
    discount: "25% OFF",
    rating: 4.4,
    reviews: 650,
    labels: ["25% OFF"],
    image: "/images/products/tshirt.jpeg",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black & White", "Blue & White"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
  {
    id: 8,
    name: "Black Oversized Shirt",
    store: "Urban Tribe",
    price: 549,
    oldPrice: 899,
    discount: "39% OFF",
    rating: 4.3,
    reviews: 920,
    labels: ["Best Seller"],
    image: "/images/products/jacket.jpeg",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Stone"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "Low Stock",
  },
  {
    id: 9,
    name: "Black Mandarin Shirt",
    store: "Ethnic Villa",
    price: 699,
    oldPrice: 1099,
    discount: "36% OFF",
    rating: 4.6,
    reviews: 480,
    labels: ["New"],
    image: "/images/bestsellers/cotton-kurta.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Mustard"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
  {
    id: 10,
    name: "Black Printed Shirt",
    store: "Street Style",
    price: 699,
    oldPrice: 999,
    discount: "30% OFF",
    rating: 4.5,
    reviews: 720,
    labels: ["Fast Delivery"],
    image: "/images/products/shirt.jpeg",
    sizes: ["M", "L", "XL"],
    colors: ["Black Printed", "Navy Printed"],
    deliveryEstimate: "Delivery in 2 Hours",
    stockStatus: "In Stock",
  },
  {
    id: 11,
    name: "Floral Dress",
    store: "Miss Boutique",
    price: 1199,
    oldPrice: 1999,
    discount: "40% OFF",
    rating: 4.8,
    reviews: 1350,
    labels: ["Hot Buy"],
    image: "/images/products/dress.jpeg",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Floral Cream", "Floral Pink"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "In Stock",
  },
  {
    id: 12,
    name: "Denim Jacket",
    store: "Urban Tribe",
    price: 1299,
    oldPrice: 1999,
    discount: "35% OFF",
    rating: 4.6,
    reviews: 1900,
    labels: ["Trending"],
    image: "/images/products/jacket.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue Denim", "Black Denim"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
  {
    id: 13,
    name: "Printed Kurta",
    store: "Ethnic Villa",
    price: 999,
    oldPrice: 1599,
    discount: "37% OFF",
    rating: 4.7,
    reviews: 1100,
    labels: ["Ethic Choice"],
    image: "/images/products/kurta.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Maroon", "Navy"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "In Stock",
  },
  {
    id: 14,
    name: "Oversized T-Shirt",
    store: "Street Style",
    price: 549,
    oldPrice: 799,
    discount: "31% OFF",
    rating: 4.5,
    reviews: 950,
    labels: ["Best Seller"],
    image: "/images/products/tshirt.jpeg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Stone"],
    deliveryEstimate: "Delivery Today",
    stockStatus: "In Stock",
  },
  {
    id: 15,
    name: "Sneakers White",
    store: "Urban Tribe",
    price: 1999,
    oldPrice: 2999,
    discount: "33% OFF",
    rating: 4.8,
    reviews: 2400,
    labels: ["Popular"],
    image: "/images/products/shoe.jpeg",
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    colors: ["White", "Black"],
    deliveryEstimate: "Delivery Tomorrow",
    stockStatus: "In Stock",
  },
];
